DROP TABLE PrestacionServicio CASCADE CONSTRAINTS;
DROP TABLE OrdenServicio CASCADE CONSTRAINTS;
DROP TABLE IPS_Medico CASCADE CONSTRAINTS;
DROP TABLE Medico CASCADE CONSTRAINTS;
DROP TABLE Beneficiario CASCADE CONSTRAINTS;
DROP TABLE Afiliado CASCADE CONSTRAINTS;
DROP TABLE IPS_TipoServicio CASCADE CONSTRAINTS;
DROP TABLE TipoServicio CASCADE CONSTRAINTS;
DROP TABLE IPS CASCADE CONSTRAINTS;

